### ISSUE TITLE
arguments

### ISSUE THREAD

**Issue by jshwlkr** [powpingdone/rus-lavi#1]
Maybe I'm doing it wrong, but `./rus-lavi one.jpg two.jpg --output test.jpg` seems to re-generate the `two.jpg` as the `test.jpg` for me.

**Comment by powpingdone** [comment]
What were the two images input?

**Comment by jshwlkr** [comment]
https://www.flickr.com/photos/michigan-engineering/51732729572/
https://www.flickr.com/photos/michigan-engineering/51734203459/

**Comment by powpingdone** [comment]
Ok, I just pushed a commit fixing a *very* silly logic mistake, though I've also realized that the model is non-deterministic and is based on the order of the images.

**Comment by powpingdone** [comment]
Did the most recent commit fix that?

**Comment by jshwlkr** [comment]
Yep!
